---
app:
  name: my-application
  version: 1.0.0

server:
  port: 8080
  host: 0.0.0.0

database:
  host: localhost
  port: 5432
  user: db_user
  password: db_password
  name: my_database

logging:
  level: info
