---
# 01_ns.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: demo-ingress

---
# 02_deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp-deployment
  namespace: demo-ingress
  labels:
    app: goapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
        - name: web
          image: ksxack/lesson1:v0.2
          ports:
            - containerPort: 8080

---
# 03_service.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: demo-ingress
  name: goweb-svc
spec:
  selector:
    app: goapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
# 04_ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  namespace: demo-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: hello-world.example
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: goweb-svc
                port:
                  number: 80
