---
apiVersion: v1
kind: Namespace
metadata:
  name: rolling
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp-deployment
  namespace: rolling
  labels:
    app: goapp
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  # Не более одного недоступного Пода во время обновления
      maxSurge: 1        # Одновременно можно создавать один новый Под
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
        test: test01
    spec:
      containers:
        - name: web
          image: ilyabobrusev/lesson1:v0.2
          ports:
            - containerPort: 8080
