---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-with-env
  namespace: demo-cm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: app
          image: busybox
          command: ["/bin/sh", "-c", "echo \"Log Level: $LOG_LEVEL, Database URL: $DATABASE_URL\" && sleep 3600"]
          envFrom:
            - configMapRef:
                name: env-config
