---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-with-cm
  namespace: demo-cm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: app
          image: busybox
          command: ["/bin/sh", "-c", "cat /etc/config/* && sleep 3600"]
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: first-cm
